#ifndef _eyes_h
#define _eyes_h

#define EYES_SHUT_0 "       ' ~-  ~~-:      . '"
#define EYES_SHUT_1 "        '= \\  ='      /\\\\ '"
#define EYES_ANGRY_0 "       ' ><   ><       . '"
#define EYES_ANGRY_1 "        '\\x\\  /x      /\\\\ '"
#define EYES_FILL_0 "       ' ><   ><       . '"
#define EYES_FILL_1 "        '⬤ \\  ⬤       /\\\\ '"
#define EYES_NONE_0 "       ' -    --       . '"
#define EYES_NONE_1 "        '  \\          /\\\\ '"
#define EYES_TARGET_0 "       ' ><   ><       . '"
#define EYES_TARGET_1 "        'ↂ \\  ↂ       /\\\\ '"
#define EYES_LOVE_0 "       ' ''  \"\"\":      . '"
#define EYES_LOVE_1 "        '♥ \\  ♥       /\\\\ '"
#define EYES_CLOSED_0 "       '--'  \"--:      . '"
#define EYES_CLOSED_1 "        '- \\  --      /\\\\ '"
#define EYES_OPEN_0 "       ' ''  \"\"\":      . '"
#define EYES_OPEN_1 "        'o \\  o       /\\\\ '"
#define EYES_BIG_WHITE_0 "       ' ''  \"\"\":      . '"
#define EYES_BIG_WHITE_1 "        '◯ \\  ◯       /\\\\ '"
#define EYES_BIG_0 "       ' ''  \"\"\":      . '"
#define EYES_BIG_1 "        '❉ \\  ❉       /\\\\ '"
#define EYES_WIGGLE_0 "       ' ^^  ^^~:      . '"
#define EYES_WIGGLE_1 "        '~ \\  ~'      /\\\\ '"
#define EYES_MONEY_0 "       ' ==  ===:      . '"
#define EYES_MONEY_1 "        ($)\\ ($_      /\\\\ '"
#define EYES_QUESTION_0 "       '--'  \"--:      . '"
#define EYES_QUESTION_1 "        (?)\\ (?)      /\\\\ '"
#endif
