#ifndef _hair_h
#define _hair_h

#define HAIR_HORNS_0 "     |\\      _-.-*`--.    /|"
#define HAIR_HORNS_1 "     \\ \\  .\"* \\\\\\\\\\\\\\\\\\\\ / ;"
#define HAIR_HORNS_2 "      \\ \\*     \\\\\\\\\\?\\\\;/ /"
#define HAIR_HORNS_3 "       ||  <o>   \\|\\|\\|/-/\\\"
#define HAIR_HORNS_4 "       ?           \\\\\\|||\\\\\"
#define HAIR_1_0 "             _-.-*`--."
#define HAIR_1_1 "          .\"* \\\\\\\\|\\\\\\\\\\\"
#define HAIR_1_2 "         *     \\|\\|\\|\\|\\\\\\\"
#define HAIR_1_3 "       //        \\|\\|\\\\\\|\\\\\"
#define HAIR_1_4 "       ?           ?\\\\|||\\\\\"
#define HAIR_1_5 "q"
#define HAIR_HASH_0 "             _-.-*`--."
#define HAIR_HASH_1 "          .\"* ##########"
#define HAIR_HASH_2 "         *     ###########"
#define HAIR_HASH_3 "       ##        ##########"
#define HAIR_HASH_4 "       ?           ########"
#define HAIR_HASH_5 "q"
#define HAIR_3_0 "             _-.-*`--."
#define HAIR_3_1 "          .\"* \\\\\\\\\\\\\\\\\\\\\"
#define HAIR_3_2 "         *     ////\\?|\\\\\\?"
#define HAIR_3_3 "       ?|        //\\|\\|\\|\\\\\"
#define HAIR_3_4 "       ?            \\\\|?|\\\\\"
#define HAIR_3_5 "q"
#define HAIR_2_0 "             _-.-*`--."
#define HAIR_2_1 "          .\"* \\\\\\??\\\\?\\\\\"
#define HAIR_2_2 "         *     \\?\\?\\\\?\\\\\\\\\"
#define HAIR_2_3 "       ?|        \\|\\?\\|?|\\\\\"
#define HAIR_2_4 "       ?           \\\\\\|||\\\\\"
#define HAIR_2_5 "q"
#define HAIR_4_0 "             _-.-*`--."
#define HAIR_4_1 "          .\"* ?\\!\\!\\\\\\!\\\"
#define HAIR_4_2 "         *     ?\\!\\!\\!\\!\\\\\"
#define HAIR_4_3 "       //        ?|!|\\|\\|\\\\\"
#define HAIR_4_4 "       ?           >\\?|||\\\\\"
#define HAIR_4_5 "q"
#define HAIR_0_0 "             _-.-*`--."
#define HAIR_0_1 "          .\"* \\\\\\\\\\\\\\\\\\\\\"
#define HAIR_0_2 "         *     \\\\\\\\\\\\\\\\\\\\\\\"
#define HAIR_0_3 "       ||        \\|\\|\\|\\|\\\\\"
#define HAIR_0_4 "       ?           \\\\\\|||\\\\\"
#define HAIR_0_5 "q"
#endif
