#ifndef _mouth_h
#define _mouth_h

#define MOUTH_WIGGLE_0 "          /__\\          ?"
#define MOUTH_WIGGLE_1 "          '≈≈           $"
#define MOUTH_WIGGLE_2 "�"
#define MOUTH_YES_0 "          /  \\          ?"
#define MOUTH_YES_1 "          (yes)        $"
#define MOUTH_YES_2 "q"
#define MOUTH_TOUNGE_0 "   _/⎺⎺⎺\\_---\\          ?"
#define MOUTH_TOUNGE_1 "  +__/ \\___/_/         $"
#define MOUTH_TOUNGE_2 ""
#define MOUTH_OOH_0 "          /  \\          ?"
#define MOUTH_OOH_1 "          |❨❩          $"
#define MOUTH_SHUT_0 "          /__\\          ?"
#define MOUTH_SHUT_1 "           ⎺⎺           $"
#define MOUTH_SHUT_2 "�"
#define MOUTH_NORMAL_0 "          /__\\          ?"
#define MOUTH_NORMAL_1 "          '--'         $"
#define MOUTH_NORMAL_2 "q"
#define MOUTH_FILL_0 "          /__\\          ?"
#define MOUTH_FILL_1 "          '▓▓          $"
#define MOUTH_SHOUT_0 "          /__\\          ?"
#define MOUTH_SHOUT_1 "          <__>         $"
#define MOUTH_SHOUT_2 "q"
#define MOUTH_NO_0 "          /  \\          ?"
#define MOUTH_NO_1 "          (no)        $"
#define MOUTH_NO_2 ""
#define MOUTH_OPEN_0 "          /--\\          ?"
#define MOUTH_OPEN_1 "          '__/         $"
#define MOUTH_OPEN_2 "q"
#endif
